import { prisma } from "@/lib/db";
import { highlightSetHash } from "@/lib/hash";
import { getProvider } from "@/lib/ai/provider";
import { PROMPT_VERSION } from "@/lib/ai/prompts";

export { PROMPT_VERSION };

/**
 * The model id that identifies an analysis run. Part of the cache key, so
 * switching models correctly misses the cache rather than serving output
 * generated by a different one.
 */
export function currentModel(): string {
  return getProvider().model;
}

/** Content address of a book's current highlight set (SPEC 4.4). */
export async function currentHighlightSetHash(
  bookId: string,
): Promise<{ hash: string; count: number }> {
  const highlights = await prisma.highlight.findMany({
    where: { bookId },
    select: { contentHash: true },
  });
  return {
    hash: highlightSetHash(highlights.map((h) => h.contentHash)),
    count: highlights.length,
  };
}

/** The newest analysis for a book, whatever its status. */
export async function latestAnalysis(bookId: string) {
  return prisma.analysis.findFirst({
    where: { bookId },
    orderBy: { createdAt: "desc" },
  });
}
