import { z } from "zod";

export const TakeawaySchema = z.object({
  title: z.string().max(80),
  body: z.string(), // 2–4 sentences, second person, concrete
  theme: z.string().max(40),
  highlightIds: z.array(z.string()).min(1),
});

export const TakeawaysSchema = z.object({
  takeaways: z.array(TakeawaySchema).min(3).max(5),
});

export const ChapterSchema = z.object({
  number: z.number().int().nullable(), // null for prefaces, epilogues, parts
  title: z.string(),
  summary: z.string(), // 2–4 sentences
  keyIdeas: z.array(z.string()).max(4),
  confidence: z.enum(["high", "medium", "low"]),
});

export const ChapterOutlineSchema = z.object({
  bookRecognized: z.boolean(),
  chapters: z.array(ChapterSchema),
  caveat: z.string().nullable(),
});

/** MAP step output — candidate themes carrying their own [H<n>] citations. */
export const CandidateThemeSchema = z.object({
  theme: z.string().max(40),
  claim: z.string(),
  highlightIds: z.array(z.string()).min(1),
});

export const CandidateThemesSchema = z.object({
  candidates: z.array(CandidateThemeSchema),
});

export type Takeaway = z.infer<typeof TakeawaySchema>;
export type Takeaways = z.infer<typeof TakeawaysSchema>;
export type Chapter = z.infer<typeof ChapterSchema>;
export type ChapterOutline = z.infer<typeof ChapterOutlineSchema>;
export type CandidateTheme = z.infer<typeof CandidateThemeSchema>;

/**
 * Read-side parsers for the `takeaways` / `chapters` JSONB columns. A payload
 * written by an older prompt version that no longer parses renders as
 * "generated by an older version — regenerate", never as a crash (SPEC 4.5).
 */
export function parseStoredTakeaways(value: unknown): Takeaway[] | null {
  const result = TakeawaysSchema.safeParse(value);
  return result.success ? result.data.takeaways : null;
}

export function parseStoredChapters(value: unknown): Chapter[] | null {
  const result = z.array(ChapterSchema).safeParse(value);
  return result.success ? result.data : null;
}

export const ChaptersMetaSchema = z.object({
  bookRecognized: z.boolean(),
  caveat: z.string().nullable().optional(),
});

export type ChaptersMeta = z.infer<typeof ChaptersMetaSchema>;

export function parseStoredChaptersMeta(value: unknown): ChaptersMeta | null {
  const result = ChaptersMetaSchema.safeParse(value);
  return result.success ? result.data : null;
}
